Wrap init of booleans' values in try-catch
Android versions before Nougat do not have `getByte` method in `sun.misc.Unsafe`. This causes loading of LongHashFunction to trigger NoSuchMethodError when running on older versions of platform (see #18 for details).